

# Regression Models with Keras

<a id="item31"></a>

## Download and Clean the  Data Set

In [4]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

Let's download the data and read it into a <em>pandas</em> dataframe.

In [5]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

#### Let's check how many data points we have

In [6]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

Let's check the dataset for any missing values.

In [7]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [8]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [9]:
concrete_data_columns = concrete_data.columns

In [10]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

<a id="item2"></a>

Let's do a quick sanity check of the predictors and the target dataframes.

In [11]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [12]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [13]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [14]:
n_cols = predictors_norm.shape[1] # number of predictors

<a id="item1"></a>

<a id='item32'></a>

##  Import Keras Packages

##### Let's import the rest of the packages from the Keras library that we will need to build our regression model.

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [16]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

<a id="item4"></a>

## Train and Test the Network

Let's call the function now to create our model.

In [17]:
# build the model
model = regression_model()

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [18]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 72ms/step - loss: 1636.5938 - val_loss: 1132.7036
Epoch 2/100
23/23 - 0s - 5ms/step - loss: 1485.5973 - val_loss: 984.0303
Epoch 3/100
23/23 - 0s - 6ms/step - loss: 1241.3539 - val_loss: 762.5143
Epoch 4/100
23/23 - 0s - 6ms/step - loss: 898.5352 - val_loss: 499.2200
Epoch 5/100
23/23 - 0s - 5ms/step - loss: 542.7352 - val_loss: 278.4428
Epoch 6/100
23/23 - 0s - 6ms/step - loss: 313.5350 - val_loss: 179.6193
Epoch 7/100
23/23 - 0s - 5ms/step - loss: 246.4433 - val_loss: 158.1072
Epoch 8/100
23/23 - 0s - 6ms/step - loss: 227.2221 - val_loss: 161.3339
Epoch 9/100
23/23 - 0s - 5ms/step - loss: 214.9392 - val_loss: 160.2204
Epoch 10/100
23/23 - 0s - 6ms/step - loss: 205.9925 - val_loss: 158.3694
Epoch 11/100
23/23 - 0s - 5ms/step - loss: 198.3180 - val_loss: 157.3461
Epoch 12/100
23/23 - 0s - 6ms/step - loss: 191.9931 - val_loss: 154.0814
Epoch 13/100
23/23 - 0s - 6ms/step - loss: 186.2961 - val_loss: 154.6353
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 181.0428 - val_loss: 150.1712
Epoch 15/100
23/23 - 0s - 5ms/step - loss: 177.0548 - val_loss: 151.7593
Epoch 16/100
23/23 - 0s - 5ms/step - loss: 172.8036 - val_loss: 149.2201
Epoch 17/100
23/23 - 0s - 5ms/step - loss: 169.2225 - val_loss: 148.8318
Epoch 18/100
23/23 - 0s - 6ms/step - loss: 166.7545 - val_loss: 146.1012
Epoch 19/100
23/23 - 0s - 6ms/step - loss: 163.4009 - val_loss: 146.6500
Epoch 20/100
23/23 - 0s - 6ms/step - loss: 160.5506 - val_loss: 146.8752
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 158.1684 - val_loss: 145.8627
Epoch 22/100
23/23 - 0s - 6ms/step - loss: 156.0071 - val_loss: 145.2854
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 153.9890 - val_loss: 145.8881
Epoch 24/100
23/23 - 0s - 5ms/step - loss: 151.3375 - val_loss: 145.3054
Epoch 25/100
23/23 - 0s - 5ms/step - loss: 150.2130 - val_loss: 144.7399
Epoch 26/100
23/23 - 0s - 6ms/step - loss: 147.9183 - val_loss: 145.8765
Epoch 27/100
23/23 - 0s - 6ms/step - loss: 146.3812 - val_loss: 145.8092
Epoch 28/100
23/23 - 0s - 5ms/step - loss: 144.5705 - val_loss: 146.3492
Epoch 29/100
23/23 - 0s - 5ms/step - loss: 142.9628 - val_loss: 146.6250
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 141.4935 - val_loss: 146.5838
Epoch 31/100
23/23 - 0s - 6ms/step - loss: 140.1138 - val_loss: 144.2041
Epoch 32/100
23/23 - 0s - 6ms/step - loss: 138.2702 - val_loss: 145.3435
Epoch 33/100
23/23 - 0s - 5ms/step - loss: 136.9900 - val_loss: 147.0305
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 135.5359 - val_loss: 144.8594
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 134.2029 - val_loss: 146.0143
Epoch 36/100
23/23 - 0s - 5ms/step - loss: 133.0625 - val_loss: 146.6021
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 131.5655 - val_loss: 146.9570
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 130.2174 - val_loss: 144.8869
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 127.9058 - val_loss: 146.3346
Epoch 40/100
23/23 - 0s - 8ms/step - loss: 126.9641 - val_loss: 145.9579
Epoch 41/100
23/23 - 0s - 9ms/step - loss: 125.9427 - val_loss: 147.2910
Epoch 42/100
23/23 - 0s - 9ms/step - loss: 124.1289 - val_loss: 147.7779
Epoch 43/100
23/23 - 0s - 9ms/step - loss: 123.0833 - val_loss: 148.5633
Epoch 44/100
23/23 - 0s - 8ms/step - loss: 122.0769 - val_loss: 148.3189
Epoch 45/100
23/23 - 0s - 8ms/step - loss: 119.6522 - val_loss: 146.6433
Epoch 46/100
23/23 - 0s - 8ms/step - loss: 117.8502 - val_loss: 143.5078
Epoch 47/100
23/23 - 0s - 8ms/step - loss: 116.6878 - val_loss: 149.0618
Epoch 48/100
23/23 - 0s - 18ms/step - loss: 114.8187 - val_loss: 144.3331
Epoch 49/100
23/23 - 0s - 10ms/step - loss: 115.5074 - val_loss: 141.5572
Epoch 50/100
23/23 - 0s - 12ms/step - loss: 111.8611 - val_loss: 146.2537
Epoch 51/100
23/23 - 0s - 5ms/step - loss: 109.8530 - val_loss: 140.5029
Epoch 52/100
23/23 - 0s - 5ms/step - loss: 107.5733 - val_loss: 145.3810
Epoch 53/100
23/23 - 0s - 7ms/step - loss: 105.6150 - val_loss: 143.5184
Epoch 54/100
23/23 - 0s - 6ms/step - loss: 103.5020 - val_loss: 142.8101
Epoch 55/100
23/23 - 0s - 5ms/step - loss: 101.0730 - val_loss: 139.7555
Epoch 56/100
23/23 - 0s - 6ms/step - loss: 98.3569 - val_loss: 140.5598
Epoch 57/100
23/23 - 0s - 6ms/step - loss: 96.5489 - val_loss: 142.5993
Epoch 58/100
23/23 - 0s - 6ms/step - loss: 94.2718 - val_loss: 142.3732
Epoch 59/100
23/23 - 0s - 5ms/step - loss: 92.0624 - val_loss: 139.0357
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 89.5682 - val_loss: 136.2138
Epoch 61/100
23/23 - 0s - 6ms/step - loss: 86.9963 - val_loss: 136.9109
Epoch 62/100
23/23 - 0s - 5ms/step - loss: 84.5675 - val_loss: 137.8680
Epoch 63/100
23/23 - 0s - 6ms/step - loss: 81.8942 - val_loss: 133.1928
Epoch 64/100
23/23 - 0s - 6ms/step - loss: 79.6036 - val_loss: 135.2965
Epoch 65/100
23/23 - 0s - 6ms/step - loss: 77.4076 - val_loss: 133.5873
Epoch 66/100
23/23 - 0s - 5ms/step - loss: 75.1326 - val_loss: 133.2928
Epoch 67/100
23/23 - 0s - 6ms/step - loss: 73.1615 - val_loss: 129.2611
Epoch 68/100
23/23 - 0s - 7ms/step - loss: 71.3823 - val_loss: 126.4468
Epoch 69/100
23/23 - 0s - 12ms/step - loss: 68.7410 - val_loss: 126.5688
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 66.3724 - val_loss: 121.4188
Epoch 71/100
23/23 - 0s - 6ms/step - loss: 64.1429 - val_loss: 124.6783
Epoch 72/100
23/23 - 0s - 6ms/step - loss: 62.2789 - val_loss: 123.1098
Epoch 73/100
23/23 - 0s - 6ms/step - loss: 60.4993 - val_loss: 122.7502
Epoch 74/100
23/23 - 0s - 6ms/step - loss: 59.2308 - val_loss: 123.3870
Epoch 75/100
23/23 - 0s - 6ms/step - loss: 57.3827 - val_loss: 122.7642
Epoch 76/100
23/23 - 0s - 6ms/step - loss: 55.4493 - val_loss: 116.8439
Epoch 77/100
23/23 - 0s - 5ms/step - loss: 54.3578 - val_loss: 118.1481
Epoch 78/100
23/23 - 0s - 6ms/step - loss: 52.7804 - val_loss: 128.1506
Epoch 79/100
23/23 - 0s - 6ms/step - loss: 52.0852 - val_loss: 116.2140
Epoch 80/100
23/23 - 0s - 6ms/step - loss: 49.9178 - val_loss: 121.9647
Epoch 81/100
23/23 - 0s - 5ms/step - loss: 48.9156 - val_loss: 118.3954
Epoch 82/100
23/23 - 0s - 6ms/step - loss: 48.1175 - val_loss: 115.9673
Epoch 83/100
23/23 - 0s - 6ms/step - loss: 46.5641 - val_loss: 121.5288
Epoch 84/100
23/23 - 0s - 6ms/step - loss: 46.3000 - val_loss: 119.8939
Epoch 85/100
23/23 - 0s - 6ms/step - loss: 45.5004 - val_loss: 120.2509
Epoch 86/100
23/23 - 0s - 6ms/step - loss: 44.2633 - val_loss: 118.7316
Epoch 87/100
23/23 - 0s - 6ms/step - loss: 44.5892 - val_loss: 113.2350
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 42.7456 - val_loss: 118.4748
Epoch 89/100
23/23 - 0s - 6ms/step - loss: 42.2554 - val_loss: 120.4022
Epoch 90/100
23/23 - 0s - 6ms/step - loss: 41.2746 - val_loss: 117.4925
Epoch 91/100
23/23 - 0s - 6ms/step - loss: 40.8451 - val_loss: 120.2010
Epoch 92/100
23/23 - 0s - 6ms/step - loss: 40.5479 - val_loss: 115.6938
Epoch 93/100
23/23 - 0s - 5ms/step - loss: 39.9311 - val_loss: 123.1906
Epoch 94/100
23/23 - 0s - 6ms/step - loss: 39.5102 - val_loss: 123.7168
Epoch 95/100
23/23 - 0s - 6ms/step - loss: 39.1598 - val_loss: 113.2693
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 38.2503 - val_loss: 127.7927
Epoch 97/100
23/23 - 0s - 5ms/step - loss: 38.0086 - val_loss: 118.0446
Epoch 98/100
23/23 - 0s - 5ms/step - loss: 37.2590 - val_loss: 109.9932
Epoch 99/100
23/23 - 0s - 6ms/step - loss: 37.1730 - val_loss: 122.8328
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 36.8351 - val_loss: 122.0679